/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.10.8.0 (NJsonSchema v10.3.11.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming
//----------------------
// liquid模板语法： https://liquid.bootcss.com

import { apiSendAsync } from '../utils/apiRequest';
import { ApiResponseData, PagedList } from '../utils/apiModels';

export namespace Base {

    /**
     * 获取分类
     * @param username username
     * @return OK
     */
    export async function getnav_GET(query:{  username?: string; }){
        return apiSendAsync<ApiResponseData<BizNav[]>>('GET', '/api/base/getnav', null,query );
    }

    /**
     * 用户登录
     * @param body 用户名, 密码
     * @return OK
     */
    export async function login_POST(body: LoginStruct){
        return apiSendAsync<ApiResponseData<LoginResponse>>('POST', '/api/base/login', body, null );
    }

    /**
     * 用户注册
     * @param body 用户名, 密码, 邮箱
     * @return OK
     */
    export async function register_POST(body: RegisterUser){
        return apiSendAsync<ApiResponseData<SysUserResponse>>('POST', '/api/base/register', body, null );
    }
}

export namespace Nav {

    /**
     * 新建分类
     * @return OK
     */
    export async function create_POST(body: CreateBizNav){
        return apiSendAsync<ApiResponseData<BizNav>>('POST', '/api/nav/create', body, null );
    }

    /**
     * 删除分类
     * @param id 分类id
     * @return ok
     */
    export async function delete_DELETE(query:{  id?: number; }){
        return apiSendAsync<ApiResponseData<string>>('DELETE', '/api/nav/delete', null,query );
    }

    /**
     * 编辑分类
     * @return OK
     */
    export async function edit_POST(body: EditBizNav){
        return apiSendAsync<ApiResponseData<BizNav>>('POST', '/api/nav/edit', body, null );
    }
}

export namespace User {

    /**
     * 当前用户信息
     * @return OK
     */
    export async function currentUser_GET(){
        return apiSendAsync<ApiResponseData<SysUserResponse>>('GET', '/api/user/currentUser', null, null );
    }
}

export interface BizNav {
    /** 创建时间 */
    created_at?: string | undefined;
    /** 分类图标路径 */
    iconPath?: string | undefined;
    /** 主键ID */
    id?: number | undefined;
    /** 是否公开 */
    isPublic?: boolean | undefined;
    /** 分类名称 */
    navName: string;
    /** 更新时间 */
    updated_at?: string | undefined;
    /** 链接 */
    urlJson?: string | undefined;
    /** 用户名 */
    userName: string;
}

export interface SysUser {
    /** 创建时间 */
    created_at?: string | undefined;
    /** 邮箱 */
    email: string;
    /** 主键ID */
    id?: number | undefined;
    /** 角色 */
    roles?: string | undefined;
    /** 更新时间 */
    updated_at?: string | undefined;
    /** 用户名 */
    userName: string;
}

export interface CreateBizNav {
    /** 分类图标路径 */
    iconPath?: string | undefined;
    /** 是否公开 */
    isPublic?: boolean | undefined;
    /** 分类名称 */
    navName: string;
    /** 链接 */
    urlJson?: string | undefined;
}

export interface EditBizNav {
    /** 分类图标路径 */
    iconPath?: string | undefined;
    /** 分类id */
    id: number;
    /** 是否公开 */
    isPublic?: boolean | undefined;
    /** 分类名称 */
    navName: string;
    /** 链接 */
    urlJson?: string | undefined;
}

export interface LoginStruct {
    /** 密码 */
    password: string;
    /** 用户名 */
    userName: string;
}

export interface RegisterUser {
    /** 邮箱 */
    email: string;
    /** 密码 */
    password: string;
    /** 角色 */
    roles?: string | undefined;
    /** 用户名 */
    userName: string;
}

export interface LoginResponse {
    token?: string | undefined;
    user?: SysUser | undefined;
}

export interface SysUserResponse {
    /** 邮箱 */
    email?: string | undefined;
    id?: number | undefined;
    /** 角色 */
    roles?: string | undefined;
    /** 用户名 */
    userName?: string | undefined;
}